site_name: ""
nav:
    - Home: 'index.md'
    - 'Create on Golem':
      - 'creators/index.md'
      - JavaScript:
          - 'creators/javascript/index.md'
          - Quickstart: 'creators/javascript/quickstart.md'
          - 'Introduction to Task API':
            - 'creators/javascript/high-level/index.md'
            - 'Task Model': 'creators/javascript/high-level/task-model.md'
            - Examples:
                - '#0 - Hello World': 'creators/javascript/examples/hello.md'
                - '#1 - Simple Usage': 'creators/javascript/examples/simple.md'
                - '#2 - Hashcat on Golem': 'creators/javascript/examples/hashcat.md'
                - '#3 - Requestor in browser': 'creators/javascript/examples/web.md'
          - 'Diving deeper with Core API':
            - 'creators/javascript/mid-level/index.md'
            - Examples:
                - '#0 - Hello World': 'creators/javascript/mid-level/examples/hello.md'
                - '#1 - Requestor in browser': 'creators/javascript/mid-level/examples/web.md'
          - 'API Reference':
            - 'creators/javascript/docs/readme.md'
            - 'Table of Contents': 'creators/javascript/docs/index.md'
            - 'Classes': 'creators/javascript/docs/classes'
            - 'Enums': 'creators/javascript/docs/enums'
            - 'Interfaces': 'creators/javascript/docs/interfaces'
            - 'Modules': 'creators/javascript/docs/modules'
      - 'Decentralized apps on Golem':
          - 'creators/dapps/index.md'
          - Quickstart: 'creators/dapps/run-a-dapp.md'
          - 'Hello World dApp': 'creators/dapps/hello-world-dapp.md'
          - 'Managing multiple dApps': 'creators/dapps/dapp-manager.md'
          - 'Creating Golem dApps': 'creators/dapps/creating-golem-dapps.md'
          - 'Differences between Docker containers and Golem VM runtime': 'creators/dapps/docker-containers-vs-golem-vms.md'
          - Troubleshooting: 'creators/dapps/troubleshooting.md'
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_css:
  - css/custom-global.css
theme:
  icon:
    # repo: fontawesome/brands/github
    admonition: # this one and below are hard-coded admonition types, changed to other icons:
      abstract: fontawesome/solid/book # this one is default
      quote: fontawesome/solid/arrow-left
      question: fontawesome/solid/arrow-right
  name: material
  custom_dir: material
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
repo_url: https://github.com/golemfactory/golem-docs
copyright: >
  Copyright &copy; 2023 Golem Network â€“
  <a href="#__consent">Change cookie settings</a>
plugins:
  - search
  - include_dir_to_nav
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/golemfactory
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/golem-network
    - icon: fontawesome/brands/discord
      link: https://chat.golem.network/
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-DCDK1DXDSN
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            submitting an issue on our <a href="https://github.com/golemfactory/golem-docs/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">GitHub repository</a>.
